baseurl: "/docs.dego"
apiname: "DEGO Documentatie"
versie-nr: "1.0.7"
restAPI-Alternatief: "Nee"
url: "http://localhost:4000"
title: Data Energie Gebouwde Omgeving (DEGO)

# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt ge√∂pend.
nav:
  - title: Data Energie Gebouwde Omgeving (DEGO)
    subnav:
      - title: Home
        path: /
      - title: Vleermuizen
        path: /themas/vleermuizen_en_isolatie
      - title: Warmteprogramma
        path: /themas/warmteprogramma
      - title: API Documentatie
        path: /API

apinav:
  - title: Data Energie Gebouwde Omgeving (DEGO)
    subnav:
      - title: Home
        path: /
      - title: Vleermuizen
        path: /themas/vleermuizen_en_isolatie
      - title: Warmteprogramma
        path: /themas/warmteprogramma
      - title: API Documentatie
        path: /API

apisubnav: 
  - subnav:
      - title: API Energie data
        path: /API/energie_api 
      - title: WFS - energie
        path: /API/energie_wfs  
      - title: WFS - cbs
        path: /API/cbs_wfs
      - title: Vector tiles
        path: /API/vt  

themanav:
  - title: Data Energie Gebouwde Omgeving (DEGO)
    subnav:
      - title: Home
        path: /
      - title: Vleermuizen
        path: /themas/vleermuizen_en_isolatie
      - title: Warmteprogramma
        path: /themas/warmteprogramma

        
themasubnav:
  - subnav:
      - title: Gebouwen
        path: /themas/gebouwen
      - title: Nutsvoorziening
        path: /themas/nutsvoorziening
      - title: Referentieverbruik warmte woningen
        path: /themas/referentieverbruik
      - title: Energie verbruik
        path: /themas/energie_verbruik
      - title: Bewoners
        path: /themas/bewoners
      - title: Koppelkansen
        path: /themas/koppelkansen

        
themafooter:
  - subnav:
      - title: API Documentatie
        path: /API 


plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: michielverhoef/jekyll-theme-vngrealisatie-kcdenm

github: michielverhoef/docs.dego

theme: jekyll-theme-time-machine

project_name: VNG-Realisatie/DEGO

standard_family: WSJG
