baseurl: "/docs.dego"
apiname: "DEGO Documentatie"
versie-nr: "1.0.7"
restAPI-Alternatief: "Nee"
url: "http://localhost:4000"

# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt ge√∂pend.
nav:
  - title: Data Energie Gebouwde Omgeving (DEGO)
    subnav:
      - title: Home
        path: /
      - title: Documentatie
        path: /docs 
      - title: Over CDF
        path: /over  
      - title: Contact
        path: /contact
      - title: SourceCode
        path: /sourcecode  

apinav:
  - title: API Documentatie
    subnav:
      - title: Home
        path: /
      - title: API Energie data
        path: /api/energie_api 
      - title: API BOVAG
        path: /api/bovag  
      - title: API SBICODES
        path: /api/sbicodes
      - title: API RDW
        path: /api/rdw 
      - title: WFS - energie
        path: /api/energie_wfs  
      - title: WFS - cbs
        path: /api/cbs_wfs
      - title: Vector tiles
        path: /  


plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: michielverhoef/jekyll-theme-vng-realisatie

github: michielverhoef/docs.dego

theme: jekyll-theme-time-machine

project_name: VNG-Realisatie/DEGO

standard_family: WSJG
